services:
  cloud_brain:
    image: neo4j:community
    container_name: cloud_sentinel_core
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/cloudpassword123